name: 'Python cross-platform package action'
description: 'Create cross-platform Python distribution packages with QEMU, Docker buildx, and Devcontainer'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  docker-registry:
    description: 'Docker registry'
    required: false
    default: 'docker.io'
  docker-username:
    description: 'Docker registry username'
    required: false
  docker-password:
    description: 'Docker registry password'
    required: false
  devcontainer-config:
    description: 'Devcontainer config selector (eg. architecture, OS, etc.)'
    required: false
    default: '.'
  devcontainer-command:
    description: 'Devcontainer run command'
    required: false
    default: '.devcontainer/build.sh'

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU for multi-architecture builds
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker buildx for multi-architecture builds
      uses: docker/setup-buildx-action@v2
    - if: ${{ inputs.docker-username && inputs.docker-password }}
      name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    - name: Create distributions in devcontainer
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: ${{ inputs.devcontainer-command }}
        configFile: .devcontainer/${{ inputs.devcontainer-config }}/devcontainer.json
