name: Test native Python packaging

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-library:
    name: Test creating library packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up test environment
        run: cp -R native/test/* .

      - name: Create library packages
        uses: ./native
        with:
          debian-dist-type: 'library'

      - name: Assert packages have created
        run: |
          set -e
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/python3-test-module_1.0.0_all.deb

  test-application:
    name: Test creating application packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up test environment
        run: cp -R native/test/* .

      - name: Create application packages
        uses: ./native
        with:
          debian-dist-type: 'application'

      - name: Assert packages have created
        run: |
          set -e
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-any.whl
          ls dist/test-module_1.0.0_all.deb
