name: Test cross platform Python packaging

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-arm32v7-cross:
    name: Test creating arm32v7 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: cp -a test/. .

      - name: Create packages
        uses: ./cross
        with:
          devcontainer-config: 'arm32v7'
          devcontainer-command: python setup.py sdist bdist_wheel

      - name: Assert packages have created
        run: |
          set -e
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-linux_armv7l.whl

  test-arm64v8-cross:
    name: Test creating arm64v8 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: cp -a test/. .

      - name: Create packages
        uses: ./cross
        with:
          devcontainer-config: 'arm64v8'
          devcontainer-command: python setup.py sdist bdist_wheel

      - name: Assert packages have created
        run: |
          set -e
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-linux_aarch64.whl

  test-amd64:
    name: Test creating amd64 packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        run: cp -a test/. .

      - name: Create packages
        uses: ./cross
        with:
          devcontainer-command: python setup.py sdist bdist_wheel

      - name: Assert packages have created
        run: |
          set -e
          ls dist/test-module-1.0.0.tar.gz
          ls dist/test_module-1.0.0-py3-none-linux_x86_64.whl
